/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Soldier.glb -o src/components/Soldier.jsx -k -K -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations,Text } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function SoldierGame({
  name="Player",
  animation="Twist_Dance",
  ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Soldier.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

     useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions?.[animation]?.fadeOut(0.24);
      }, [animation]);

       const textRef = useRef();

         useFrame(({ camera }) => {
           if (textRef.current) {
             textRef.current.lookAt(camera.position);
           }});



  return (
    <group ref={group} {...props} dispose={null}>

 <group ref={textRef}>
<Text
    position-y={3.8}
    fontSize={0.5}
    anchorX="center"
    anchorY="middle"
    font="fonts/PaytoneOne-Regular.ttf"
  >
    {name}
    <meshBasicMaterial color="white" />
  </Text>
  <Text
    position-y={3.78}
    position-x={0.02}
    position-z={-0.02}
    fontSize={0.5}
    anchorX="center"
    anchorY="middle"
    font="fonts/PaytoneOne-Regular.ttf"
  >
    {name}
    <meshBasicMaterial color="black" />
  </Text>
</group>

      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh1_Mesh1001" geometry={nodes.Mesh1_Mesh1001.geometry} material={materials['Material.001']} skeleton={nodes.Mesh1_Mesh1001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Soldier.glb')
