/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/viking.glb -o src/components/Viking.jsx -k -K -r public 
Author: SlagPerch 3D (https://sketchfab.com/slagperch3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-lowpoly-57344ed1b37a4bbdac3b1481f8a85a65
Title: Viking (lowpoly)
*/

import React, { useEffect, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Viking({
  name="Player",
  animation="Idle",
  ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/viking.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions?.[animation]?.fadeOut(0.24);
      }, [animation]);

      const textRef = useRef();
        useFrame(({ camera }) => {      
          if (textRef.current) {
            textRef.current.lookAt(camera.position);}});

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_48">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Boots_45" />
                  <group name="Chainmail_46" />
                  <group name="Human_viking_47" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Viking_gear} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Viking_gear} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Viking_body} skeleton={nodes.Object_11.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/viking.glb')
